// Command corpusdocs turns the corpus fixtures into a docs page you can browse
// on the site, so nobody has to keep that page in sync by hand. The fixtures are
// the source of truth; this page is generated from them.
//
// Usage (from the repo root):
//
//	go run ./cmd/corpusdocs
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"text/template"

	"github.com/joels-claude-bot/llm-site-reviewer/internal/corpus"
)

const (
	corpusRoot = "corpus"
	outPath    = "docs-site/docs/spec/corpus.md"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "corpusdocs:", err)
		os.Exit(1)
	}
}

func run() error {
	fixtures, err := corpus.Load(corpusRoot)
	if err != nil {
		return err
	}

	// Group by category, splitting each into must-flag and look-alikes.
	type group struct {
		Name      string
		Display   string
		Flag      []corpus.Fixture
		LookAlike []corpus.Fixture
	}
	byCat := map[string]*group{}
	var order []string
	for _, fx := range fixtures {
		g, ok := byCat[fx.Category]
		if !ok {
			g = &group{Name: fx.Category, Display: title(fx.Category)}
			byCat[fx.Category] = g
			order = append(order, fx.Category)
		}
		if fx.LookAlike() {
			g.LookAlike = append(g.LookAlike, fx)
		} else {
			g.Flag = append(g.Flag, fx)
		}
	}
	sort.Strings(order)
	groups := make([]*group, 0, len(order))
	for _, name := range order {
		groups = append(groups, byCat[name])
	}

	var buf strings.Builder
	if err := page.Execute(&buf, groups); err != nil {
		return err
	}
	if err := os.WriteFile(outPath, []byte(buf.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s (%d fixtures, %d categories)\n", outPath, len(fixtures), len(groups))
	return nil
}

func title(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

var page = template.Must(template.New("corpus").Parse(`---
title: Corpus
---

{{/* GENERATED by cmd/corpusdocs from the corpus/ fixtures. Do not edit by hand. */ -}}
# Corpus

This page is generated from the fixtures in ` + "`corpus/`" + `. Each fixture is a small page that
plants one defect, with the result we expect written into its own frontmatter. The reviewer runs
against these; the test checks that what it finds matches what each page says it should. See the
[test corpus](/spec/test-corpus) for how that works and the [reference](/spec/reference) for the
category codes.

Do not edit this page by hand. Change a fixture and regenerate with ` + "`go run ./cmd/corpusdocs`" + `.
{{range .}}
## {{.Display}}

These pages each plant one defect the reviewer must flag.

| Fixture | Category | Result | What is planted |
|---|---|---|---|
{{range .Flag}}| ` + "`{{.Path}}`" + ` | ` + "`{{(index .Expect 0).Category}}`" + ` | {{(index .Expect 0).Result}} | {{.Note}} |
{{end}}
{{if .LookAlike}}These look suspicious but are fine. The reviewer must report nothing.

| Fixture | Why it is fine |
|---|---|
{{range .LookAlike}}| ` + "`{{.Path}}`" + ` | {{.Note}} |
{{end}}{{end}}{{end}}`))
